// @flow
// flow-typed signature: ce3726ab8b1dcafbe5924d60999f6060
// flow-typed version: <<STUB>>/connected-react-router_v4.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connected-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
import type { Middleware, MiddlewareAPI } from 'redux'

declare module 'connected-react-router' {
  declare module.exports: {
    ConnectedRouter: React$StatelessFunctionalComponent<*>,
    connectRouter: (history: *) => (reducer: *) => *,
    routerReducer: $Exports<'connected-react-router/reducer'>,
  }
}

declare module 'connected-react-router/lib/middleware' {
  declare module.exports: $Exports<'connected-react-router/middleware'>
}

declare module 'connected-react-router/middleware' {
  declare module.exports: (history: *) => (store: MiddlewareAPI<*, *, *>) => Middleware<{}, *>
}

declare module 'connected-react-router/lib/reducer' {
  declare module.exports: $Exports<'connected-react-router/reducer'>
}

declare module 'connected-react-router/reducer' {
  declare type Location = {
    pathname: string,
    search: string,
    hash: string,
    key: string,
  }

  declare type State = {
    location: Location,
    action: ?string,
  }

  declare type Action = {
    type: string,
    payload: Object,
  }

  declare module.exports: {
    routerReducer: (state: State, action: Action) => State,
    LOCATION_CHANGE: string,
  }
}
