// flow-typed signature: 5e15e6e78a208b619129194608bdb8a1
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: Function
}
